dist: bionic

language: node_js

node_js:
  - "12"

os:
  - linux

services:
  - xvfb

addons:
  chrome: stable

sudo: required

before_install:
    - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
    - npm install 

script:
    - npm run lint
    - npm run test -- --watch=false --no-progress --code-coverage
    - npm run e2e ----protractor-config=e2e/protractor-ci.conf.js 
    # upload code coverage
    - cat ./coverage/meetup-data-scraper-angular/lcov.info | codacy-coverage
    
cache:
  directories:
    - ./node_modules