dist: trusty

language: node_js

node_js:
  - "10"

os:
  - linux

sudo: false

cache:
  directories:
    - ./node_modules

addons:
  apt:
    sources:
    - google-chrome 
    packages:
    - google-chrome-stable

install:
  - npm install 

script:
  # run tests
  - npm run test ----no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e ----protractor-config=e2e/protractor-ci.conf.js 
